#!/bin/bash

# Pockets Install Script for macOS
# Installs the addon to your WoW Classic Anniversary AddOns directory.

set -e

echo "======================================"
echo "  Pockets Addon Installer (macOS)"
echo "======================================"
echo ""

# Anniversary is the only auto-detected target - it's Pockets' primary
# client (Pockets.toc's first declared Interface version). Other Classic
# flavors aren't auto-selected; pass an explicit AddOns path as $1 for those.
ANNIVERSARY_PATHS=(
    "/Applications/World of Warcraft/_anniversary_/Interface/AddOns"
    "$HOME/Applications/World of Warcraft/_anniversary_/Interface/AddOns"
)

if [ -n "$1" ]; then
    ADDONS_DIR="$1"
    if [ ! -d "$ADDONS_DIR" ]; then
        echo "❌ Error: Specified directory does not exist: $ADDONS_DIR"
        exit 1
    fi
else
    ADDONS_DIR=""
    for path in "${ANNIVERSARY_PATHS[@]}"; do
        if [ -d "$path" ]; then
            ADDONS_DIR="$path"
            break
        fi
    done

    if [ -z "$ADDONS_DIR" ]; then
        echo "❌ Error: Could not find WoW Classic Anniversary AddOns directory"
        echo ""
        echo "Searched in:"
        for path in "${ANNIVERSARY_PATHS[@]}"; do
            echo "  - $path"
        done
        echo ""
        echo "Please ensure WoW Classic Anniversary is installed, or specify the path manually:"
        echo "  ./install.sh /path/to/WoW/_classic_or_anniversary_/Interface/AddOns"
        exit 1
    fi
fi

TARGET_DIR="$ADDONS_DIR/Pockets"
SCRIPT_DIR="$(dirname "$0")"
TOC_FILE="$SCRIPT_DIR/pockets/Pockets.toc"

# Extract version from .toc file
VERSION="unknown"
if [ -f "$TOC_FILE" ]; then
    VERSION=$(grep "^## Version:" "$TOC_FILE" | sed 's/^## Version: *//' | tr -d ' ')
fi

# Get current timestamp
INSTALL_TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S %Z')

echo "Installing to: $ADDONS_DIR"
echo "Version: $VERSION"
echo ""

# Remove existing installation if present
if [ -d "$TARGET_DIR" ]; then
    echo "Removing existing Pockets installation..."
    rm -rf "$TARGET_DIR"
fi

# Copy addon files
echo "Copying Pockets addon files..."
cp -r "$SCRIPT_DIR/pockets" "$ADDONS_DIR/"

# Create installation info file
INSTALL_INFO_FILE="$TARGET_DIR/.install_info"
cat > "$INSTALL_INFO_FILE" << EOF
# Pockets Installation Information
# This file is automatically generated by the installer

Version: $VERSION
Installed: $INSTALL_TIMESTAMP
Installer: install.sh
EOF

# Verify installation
if [ -f "$TARGET_DIR/Pockets.toc" ]; then
    echo ""
    echo "✅ Pockets installed successfully!"
    echo ""
    echo "Installation details:"
    echo "  Version: $VERSION"
    echo "  Installed: $INSTALL_TIMESTAMP"
    echo "  Location: $TARGET_DIR"
    echo ""
    echo "Next steps:"
    echo "  1. Launch or /reload World of Warcraft"
    echo "  2. Type: /pockets help"
    echo ""
    echo "Testing without in-game actions:"
    echo "  /pockets test run   - Run automated tests"
    echo ""
else
    echo "❌ Installation may have failed. Pockets.toc not found."
    exit 1
fi
